version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "book-demo"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ppqsvk49ich5"
s3_prefix = "book-demo"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
