AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Resources:
  DynamoBooksTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: books
      PrimaryKey:
        Name: id
        Type: String
  CreateBookFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: create-book.handler
      Policies: AmazonDynamoDBFullAccess
      Runtime: nodejs12.x
      Events:
        CreateBook:
          Type: Api
          Properties:
            Path: /books
            Method: post
  UpdateBookFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: update-book.handler
      Policies: AmazonDynamoDBFullAccess
      Runtime: nodejs12.x
      Events:
        CreateBook:
          Type: Api
          Properties:
            Path: /books
            Method: put
  DeleteBookFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: delete-book.handler
      Policies: AmazonDynamoDBFullAccess
      Runtime: nodejs12.x
      Events:
        CreateBook:
          Type: Api
          Properties:
            Path: /books
            Method: delete
  GetBooksFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: get-books.handler
      Policies: AmazonDynamoDBFullAccess
      Runtime: nodejs12.x
      Events:
        GetBooks:
          Type: Api
          Properties:
            Path: /books
            Method: get